// Renders the Mac app's icons (src/ui/Icons.tsx) to SVG markup for the phone,
// so both apps draw the same icons. Runs on install; the output is not committed.
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";

const app = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const desktop = resolve(app, "../../src");
const out = resolve(app, "src/ui/icons.generated.ts");
const bundle = resolve(app, "node_modules/.cache/sikemux-icons.mjs");

const entry = `
import { renderToStaticMarkup } from "react-dom/server";
import * as Icons from ${JSON.stringify(resolve(desktop, "ui/Icons.tsx"))};
export const rendered = Object.fromEntries(
  Object.entries(Icons)
    .filter(([name, Icon]) => typeof Icon === "function" && (name.startsWith("Icon") || name === "Logo"))
    .map(([name, Icon]) => [name, renderToStaticMarkup(Icon({ size: 16, percent: 80 }))]),
);
`;

mkdirSync(dirname(bundle), { recursive: true });
await build({
  stdin: { contents: entry, resolveDir: app, loader: "tsx" },
  bundle: true,
  platform: "node",
  format: "esm",
  jsx: "automatic",
  loader: { ".svg": "dataurl" },
  packages: "external",
  outfile: bundle,
  logLevel: "warning",
});
const { rendered } = await import(pathToFileURL(bundle).href);
rmSync(bundle);

// These two are drawn from files rather than inline paths.
const fromFile = { IconCodex: "codex.svg", IconOmp: "omp.svg" };
for (const [name, file] of Object.entries(fromFile)) {
  rendered[name] = readFileSync(resolve(desktop, "assets/agent-logos", file), "utf8");
}

const markup = Object.fromEntries(
  Object.entries(rendered)
    .filter(([, svg]) => svg.startsWith("<svg"))
    .map(([name, svg]) => [name, svg.replace(/ aria-hidden="true"/g, "")]),
);
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/generate-icons.mjs from src/ui/Icons.tsx. Do not edit.\n` +
    `export const ICONS = ${JSON.stringify(markup, null, 2)} as const;\n` +
    `export type IconName = keyof typeof ICONS;\n`,
);
console.log(`icons: ${Object.keys(markup).length} from the Mac app`);
