// Turns the protocol's JSON Schema documents into TypeScript types, Rust types, one bundled
// schema for validation, and an OpenAPI document. It accepts a deliberately small part of
// JSON Schema, so that every shape it allows means the same thing in both languages.

export const HEADER =
  "// Generated by server/protocol/scripts/generate.mjs from server/protocol/schema.\n// Do not edit by hand.\n";
const BUNDLE_ID = "https://api.sikemux.com/schema/v1";
const RUST_KEYWORDS = new Set([
  "type",
  "match",
  "ref",
  "self",
  "move",
  "use",
  "mod",
  "fn",
  "impl",
  "loop",
  "where",
]);
const PRIMITIVES = new Set(["string", "integer", "number", "boolean"]);
const PROPERTY_CONSTRAINTS = new Set([
  "description",
  "format",
  "pattern",
  "minLength",
  "maxLength",
  "minimum",
  "maximum",
]);
const ARRAY_CONSTRAINTS = new Set(["description", "minItems", "maxItems"]);

export class SchemaError extends Error {}

function fail(where, message) {
  throw new SchemaError(`${where}: ${message}`);
}

function onlyKeys(where, value, allowed) {
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) fail(where, `"${key}" is not supported here`);
  }
}

export function pascalCase(value) {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

function snakeCase(value) {
  return value.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

/** Reads every document's definitions into one table, keyed by name. */
export function collect(documents) {
  const definitions = new Map();
  for (const [file, document] of Object.entries(documents)) {
    onlyKeys(file, document, new Set(["$schema", "$id", "$defs"]));
    if (document.$id !== file) fail(file, `"$id" must be "${file}"`);
    for (const [name, schema] of Object.entries(document.$defs ?? {})) {
      if (!/^[A-Z][A-Za-z0-9]*$/.test(name))
        fail(`${file}#${name}`, "definition names are PascalCase");
      if (definitions.has(name))
        fail(
          `${file}#${name}`,
          `"${name}" is already defined in ${definitions.get(name).file}`,
        );
      definitions.set(name, { name, file, schema });
    }
  }
  for (const definition of definitions.values()) check(definition, definitions);
  checkTags(definitions);
  return definitions;
}

/** Each union a definition is a member of, so its tag property can be left to the union. */
function unionOf(definitions) {
  const unions = new Map();
  for (const { name, file, schema } of definitions.values()) {
    if (kindOf(schema) !== "union") continue;
    for (const member of schema.oneOf) {
      const memberName = resolveRef(name, member.$ref, file, definitions);
      if (unions.has(memberName))
        fail(
          `${file}#${name}`,
          `"${memberName}" is already a member of ${unions.get(memberName)}`,
        );
      unions.set(memberName, name);
    }
  }
  return unions;
}

/** A constant property is only ever the tag that tells a union's members apart. */
function checkTags(definitions) {
  const unions = unionOf(definitions);
  for (const { name, file, schema } of definitions.values()) {
    if (kindOf(schema) !== "object") continue;
    for (const [property, value] of Object.entries(schema.properties ?? {})) {
      if (!("const" in value)) continue;
      const union = unions.get(name);
      if (
        !union ||
        definitions.get(union).schema.discriminator.propertyName !== property
      )
        fail(
          `${file}#${name}.${property}`,
          "a constant is only for the property that tags a union's members",
        );
    }
  }
}

function tagOf(member, propertyName) {
  return member.schema.properties?.[propertyName]?.const;
}

function resolveRef(where, ref, file, definitions) {
  const match = /^(?:([a-z][a-z0-9-]*\.json))?#\/\$defs\/([A-Za-z0-9]+)$/.exec(
    ref,
  );
  if (!match) fail(where, `"${ref}" is not a reference to a definition`);
  const target = definitions.get(match[2]);
  if (!target || target.file !== (match[1] ?? file))
    fail(where, `"${ref}" points at nothing`);
  return target.name;
}

function kindOf(schema) {
  if (schema.oneOf) return "union";
  if (schema.type === "object") return "object";
  if (schema.type === "string" && schema.enum) return "enum";
  return "alias";
}

function check({ name, file, schema }, definitions) {
  const where = `${file}#${name}`;
  const kind = kindOf(schema);
  if (kind === "object") {
    onlyKeys(
      where,
      schema,
      new Set([
        "description",
        "type",
        "properties",
        "required",
        "additionalProperties",
      ]),
    );
    if (schema.additionalProperties !== false)
      fail(where, "objects must say additionalProperties: false");
    const properties = schema.properties ?? {};
    for (const required of schema.required ?? []) {
      if (!(required in properties))
        fail(where, `"${required}" is required but not a property`);
    }
    for (const [property, value] of Object.entries(properties)) {
      const at = `${where}.${property}`;
      if (!/^[a-z][A-Za-z0-9]*$/.test(property) || /[A-Z]{2}/.test(property)) {
        fail(
          at,
          "property names are camelCase words, so they convert to snake_case and back",
        );
      }
      const type = propertyType(at, value, file, definitions);
      if (type.nullable && !(schema.required ?? []).includes(property)) {
        fail(at, "a property is either optional or nullable, not both");
      }
    }
  } else if (kind === "union") {
    onlyKeys(
      where,
      schema,
      new Set(["description", "type", "oneOf", "discriminator"]),
    );
    if (schema.type !== "object")
      fail(where, `a union says type: "object", as validators need`);
    const discriminator = schema.discriminator;
    if (
      typeof discriminator !== "object" ||
      discriminator === null ||
      Object.keys(discriminator).join() !== "propertyName" ||
      typeof discriminator.propertyName !== "string"
    )
      fail(where, `a union says discriminator: { "propertyName": "type" }`);
    if (!Array.isArray(schema.oneOf) || schema.oneOf.length === 0)
      fail(where, "oneOf lists the union's members");
    const tags = new Set();
    for (const member of schema.oneOf) {
      if (
        typeof member !== "object" ||
        member === null ||
        Object.keys(member).join() !== "$ref"
      )
        fail(where, `each member of oneOf is a { "$ref": ... }`);
      const target = definitions.get(
        resolveRef(where, member.$ref, file, definitions),
      );
      const at = `${where} member ${target.name}`;
      if (kindOf(target.schema) !== "object") fail(at, "members are objects");
      const tag = tagOf(target, discriminator.propertyName);
      if (
        typeof tag !== "string" ||
        !(target.schema.required ?? []).includes(discriminator.propertyName)
      )
        fail(
          at,
          `members require "${discriminator.propertyName}" as a constant string`,
        );
      if (!/^[a-z][a-z0-9_.]*$/.test(tag))
        fail(at, `tag ${JSON.stringify(tag)} must be lowercase words`);
      if (tags.has(pascalCase(tag)))
        fail(at, `two members make the same Rust variant`);
      if (pascalCase(tag) === "Unknown")
        fail(
          at,
          `"unknown" is reserved for messages a client does not know yet`,
        );
      tags.add(pascalCase(tag));
    }
  } else if (kind === "enum") {
    onlyKeys(where, schema, new Set(["description", "type", "enum"]));
    const variants = schema.enum.map((value) => {
      if (typeof value !== "string" || !/^[a-z][a-z0-9_.]*$/.test(value)) {
        fail(
          where,
          `enum value ${JSON.stringify(value)} must be lowercase words`,
        );
      }
      return pascalCase(value);
    });
    if (new Set(variants).size !== variants.length)
      fail(where, "two enum values make the same Rust variant");
    if (variants.includes("Unknown"))
      fail(
        where,
        `"unknown" is reserved for values a client does not know yet`,
      );
  } else {
    propertyType(where, schema, file, definitions);
  }
}

/** Describes a property's type for both languages. */
function propertyType(where, schema, file, definitions) {
  if (typeof schema !== "object" || schema === null)
    fail(where, "expected a schema");
  if (schema.$ref) {
    onlyKeys(where, schema, new Set(["$ref", "description"]));
    return {
      ref: resolveRef(where, schema.$ref, file, definitions),
      nullable: false,
    };
  }
  if ("const" in schema) {
    onlyKeys(where, schema, new Set(["const", "description"]));
    if (typeof schema.const !== "string") fail(where, "a constant is a string");
    return { constant: schema.const, nullable: false };
  }
  if (schema.anyOf) {
    onlyKeys(where, schema, new Set(["anyOf", "description"]));
    const [first, second, ...rest] = schema.anyOf;
    if (rest.length || !first?.$ref || second?.type !== "null") {
      fail(where, `anyOf is only for [{ "$ref": ... }, { "type": "null" }]`);
    }
    return { ...propertyType(where, first, file, definitions), nullable: true };
  }
  let type = schema.type;
  let nullable = false;
  if (Array.isArray(type)) {
    if (type.length !== 2 || type[1] !== "null")
      fail(where, `a type list is only for ["<type>", "null"]`);
    type = type[0];
    nullable = true;
  }
  if (type === "array") {
    onlyKeys(where, schema, new Set([...ARRAY_CONSTRAINTS, "type", "items"]));
    const items = propertyType(`${where}[]`, schema.items, file, definitions);
    if (items.nullable) fail(where, "array items cannot be null");
    return { array: items, nullable };
  }
  if (!PRIMITIVES.has(type)) {
    fail(
      where,
      `type ${JSON.stringify(schema.type)} is not supported; objects and enums need their own definition`,
    );
  }
  if (schema.enum)
    fail(
      where,
      "enums need their own definition, so both languages can name them",
    );
  onlyKeys(where, schema, new Set([...PROPERTY_CONSTRAINTS, "type"]));
  if (schema.format && !["date-time", "uri"].includes(schema.format))
    fail(where, `format "${schema.format}" is not supported`);
  return { primitive: type, nullable };
}

function rewriteRefs(value, file, definitions, prefix) {
  if (Array.isArray(value))
    return value.map((item) => rewriteRefs(item, file, definitions, prefix));
  if (value === null || typeof value !== "object") return value;
  const result = {};
  for (const [key, inner] of Object.entries(value)) {
    result[key] =
      key === "$ref"
        ? `${prefix}${resolveRef(file, inner, file, definitions)}`
        : rewriteRefs(inner, file, definitions, prefix);
  }
  return result;
}

function sortedDefinitions(definitions) {
  return [...definitions.values()].sort((a, b) => a.name.localeCompare(b.name));
}

/** One schema document holding every definition, for validating requests and fixtures. */
export function bundle(definitions) {
  const $defs = {};
  for (const { name, file, schema } of sortedDefinitions(definitions)) {
    $defs[name] = rewriteRefs(schema, file, definitions, "#/$defs/");
  }
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: BUNDLE_ID,
    $defs,
  };
}

function docComment(description, indent, marker) {
  if (!description) return "";
  const lines = description.split("\n");
  if (marker === "///")
    return lines.map((line) => `${indent}/// ${line}`).join("\n") + "\n";
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
  return `${indent}/**\n${lines.map((line) => `${indent} * ${line}`).join("\n")}\n${indent} */\n`;
}

function tsType(type) {
  let base;
  if (type.constant !== undefined) base = JSON.stringify(type.constant);
  else if (type.ref) base = type.ref;
  else if (type.array) base = `${tsType(type.array)}[]`;
  else
    base = {
      string: "string",
      integer: "number",
      number: "number",
      boolean: "boolean",
    }[type.primitive];
  return type.nullable ? `${base} | null` : base;
}

export function typescript(definitions) {
  let out = HEADER;
  for (const { name, file, schema } of sortedDefinitions(definitions)) {
    out += "\n" + docComment(schema.description, "", "/**");
    const kind = kindOf(schema);
    if (kind === "object") {
      out += `export interface ${name} {\n`;
      const required = new Set(schema.required ?? []);
      for (const [property, value] of Object.entries(schema.properties ?? {})) {
        const type = propertyType(name, value, file, definitions);
        out += docComment(value.description, "  ", "/**");
        out += `  ${property}${required.has(property) ? "" : "?"}: ${tsType(type)};\n`;
      }
      out += "}\n";
    } else if (kind === "union") {
      out += `export type ${name} =\n${schema.oneOf.map((member) => `  | ${resolveRef(name, member.$ref, file, definitions)}`).join("\n")};\n`;
    } else if (kind === "enum") {
      out += `export type ${name} = ${schema.enum.map((value) => JSON.stringify(value)).join(" | ")};\n`;
    } else {
      out += `export type ${name} = ${tsType(propertyType(name, schema, file, definitions))};\n`;
    }
  }
  out +=
    "\n/** Every definition by name, so code can look a type up from the name it validates against. */\n";
  out += "export interface Definitions {\n";
  for (const { name } of sortedDefinitions(definitions))
    out += `  ${name}: ${name};\n`;
  out += "}\n";
  return out;
}

function rustType(type) {
  let base;
  if (type.ref) base = type.ref;
  else if (type.array) base = `Vec<${rustType(type.array)}>`;
  else
    base = { string: "String", integer: "i64", number: "f64", boolean: "bool" }[
      type.primitive
    ];
  return type.nullable ? `Option<${base}>` : base;
}

function rustField(property) {
  const field = snakeCase(property);
  return RUST_KEYWORDS.has(field) ? `r#${field}` : field;
}

/** Whether a type can derive Eq, which floating point numbers cannot. */
function rustEq(type, definitions, file, seen = new Set()) {
  if (type.array) return rustEq(type.array, definitions, file, seen);
  if (type.constant !== undefined) return true;
  if (type.primitive) return type.primitive !== "number";
  if (seen.has(type.ref)) return true;
  seen.add(type.ref);
  const target = definitions.get(type.ref);
  const kind = kindOf(target.schema);
  if (kind === "enum") return true;
  if (kind === "union")
    return target.schema.oneOf.every((member) =>
      rustEq(
        { ref: resolveRef(target.name, member.$ref, target.file, definitions) },
        definitions,
        target.file,
        seen,
      ),
    );
  if (kind === "alias")
    return rustEq(
      propertyType(target.name, target.schema, target.file, definitions),
      definitions,
      target.file,
      seen,
    );
  return Object.values(target.schema.properties ?? {}).every((value) =>
    rustEq(
      propertyType(target.name, value, target.file, definitions),
      definitions,
      target.file,
      seen,
    ),
  );
}

export function rust(definitions) {
  const unions = unionOf(definitions);
  let out = `${HEADER}\nuse serde::{Deserialize, Serialize};\n`;
  for (const { name, file, schema } of sortedDefinitions(definitions)) {
    out += "\n" + docComment(schema.description, "", "///");
    const kind = kindOf(schema);
    const eq = rustEq({ ref: name }, definitions, file) ? ", Eq" : "";
    if (kind === "union") {
      const tag = schema.discriminator.propertyName;
      out += `#[derive(Clone, Debug, PartialEq${eq}, Serialize, Deserialize)]\n#[serde(tag = ${JSON.stringify(tag)})]\n`;
      out += `pub enum ${name} {\n`;
      for (const member of schema.oneOf) {
        const target = definitions.get(
          resolveRef(name, member.$ref, file, definitions),
        );
        const value = tagOf(target, tag);
        out += `    #[serde(rename = ${JSON.stringify(value)})]\n    ${pascalCase(value)}(${target.name}),\n`;
      }
      out +=
        "    /// A message added after this build, which it cannot act on.\n";
      out += "    #[serde(other)]\n    Unknown,\n}\n";
    } else if (kind === "object") {
      out += `#[derive(Clone, Debug, PartialEq${eq}, Serialize, Deserialize)]\n#[serde(rename_all = "camelCase")]\n`;
      const properties = Object.entries(schema.properties ?? {}).filter(
        ([, value]) => !("const" in value),
      );
      if (properties.length === 0) {
        out += `pub struct ${name} {}\n`;
        continue;
      }
      out += `pub struct ${name} {\n`;
      const required = new Set(schema.required ?? []);
      for (const [property, value] of properties) {
        const type = propertyType(name, value, file, definitions);
        out += docComment(value.description, "    ", "///");
        if (required.has(property)) {
          out += `    pub ${rustField(property)}: ${rustType(type)},\n`;
        } else {
          out += `    #[serde(default, skip_serializing_if = "Option::is_none")]\n`;
          out += `    pub ${rustField(property)}: Option<${rustType(type)}>,\n`;
        }
      }
      out += "}\n";
    } else if (kind === "enum") {
      out +=
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]\n";
      out += `pub enum ${name} {\n`;
      for (const value of schema.enum) {
        out += `    #[serde(rename = ${JSON.stringify(value)})]\n    ${pascalCase(value)},\n`;
      }
      out +=
        "    /// A value added after this build, which it cannot act on.\n";
      out += "    #[serde(other)]\n    Unknown,\n}\n";
    } else {
      out += `pub type ${name} = ${rustType(propertyType(name, schema, file, definitions))};\n`;
    }
  }
  out +=
    "\n/// Reads `json` as the named type and writes it back, for the contract tests.\n";
  out +=
    "#[cfg(test)]\npub(crate) fn round_trip(name: &str, json: &str) -> Option<super::RoundTrip> {\n";
  out += "    use super::through;\n";
  out += "    Some(match name {\n";
  for (const { name } of sortedDefinitions(definitions))
    out += `        ${JSON.stringify(name)} => through::<${unions.get(name) ?? name}>(json),\n`;
  out += "        _ => return None,\n    })\n}\n";
  return out;
}

const AUTH = new Set(["none", "session", "device", "webhook"]);
const AUTH_NOTES = {
  device:
    "A WebSocket. The device proves who it is in its first message, since browsers cannot set headers on one. `send` is what the device sends; `receive` is what the server sends.",
  webhook: "Called by Clerk, signed with Svix's headers.",
};

/** The OpenAPI document for the HTTP routes, served to anyone who wants to read the API. */
export function openapi(definitions, routes) {
  const schemas = {};
  for (const { name, file, schema } of sortedDefinitions(definitions)) {
    schemas[name] = rewriteRefs(
      schema,
      file,
      definitions,
      "#/components/schemas/",
    );
  }
  const paths = {};
  const seen = new Set();
  for (const route of routes.routes) {
    const where = `routes.json ${route.method} ${route.path}`;
    onlyKeys(
      where,
      route,
      new Set([
        "method",
        "path",
        "operationId",
        "summary",
        "auth",
        "request",
        "query",
        "responses",
        "upgrade",
        "messages",
      ]),
    );
    if (!["get", "post", "put", "patch", "delete"].includes(route.method))
      fail(where, "unknown method");
    if (!route.path.startsWith("/v1/"))
      fail(where, "paths are versioned under /v1/");
    if (!AUTH.has(route.auth))
      fail(where, `auth is one of ${[...AUTH].join(", ")}`);
    if (route.upgrade !== undefined) {
      if (route.upgrade !== "websocket" || route.method !== "get")
        fail(where, `upgrade is "websocket", on a get`);
      if (!route.responses["101"]) fail(where, "a WebSocket route answers 101");
      onlyKeys(where, route.messages ?? {}, new Set(["send", "receive"]));
      if (!route.messages?.send || !route.messages?.receive)
        fail(
          where,
          "a WebSocket route names the messages it sends and receives",
        );
    } else if (route.messages) {
      fail(where, "only WebSocket routes have messages");
    }
    if (seen.has(route.operationId))
      fail(where, `operationId "${route.operationId}" is used twice`);
    seen.add(route.operationId);
    const named = (body) => {
      if (!definitions.has(body)) fail(where, `"${body}" is not a definition`);
      return {
        "application/json": {
          schema: { $ref: `#/components/schemas/${body}` },
        },
      };
    };
    const responses = {};
    for (const [status, response] of Object.entries(route.responses)) {
      responses[status] = {
        description: response.description,
        ...(response.body ? { content: named(response.body) } : {}),
      };
    }
    responses.default = {
      description: "Something went wrong.",
      content: named("ApiError"),
    };
    const parameters = [...route.path.matchAll(/\{([a-z][A-Za-z]*)\}/g)].map(
      ([, param]) => ({
        name: param,
        in: "path",
        required: true,
        schema: { type: "string" },
      }),
    );
    for (const [param, type] of Object.entries(route.query ?? {})) {
      if (!definitions.has(type)) {
        fail(
          where,
          `query parameter "${param}" names "${type}", which is not a definition`,
        );
      }
      parameters.push({
        name: param,
        in: "query",
        required: false,
        schema: { $ref: `#/components/schemas/${type}` },
      });
    }
    const messages = route.messages
      ? {
          "x-websocket": {
            send: named(route.messages.send)["application/json"].schema,
            receive: named(route.messages.receive)["application/json"].schema,
          },
        }
      : {};
    paths[route.path] ??= {};
    paths[route.path][route.method] = {
      operationId: route.operationId,
      summary: route.summary,
      ...(route.auth === "session" ? {} : { security: [] }),
      ...(AUTH_NOTES[route.auth]
        ? { description: AUTH_NOTES[route.auth] }
        : {}),
      ...messages,
      ...(parameters.length ? { parameters } : {}),
      ...(route.request
        ? { requestBody: { required: true, content: named(route.request) } }
        : {}),
      responses,
    };
  }
  return {
    openapi: "3.1.0",
    info: { title: "Sikemux API", version: "1" },
    servers: [{ url: "https://api.sikemux.com" }],
    paths,
    components: {
      schemas,
      securitySchemes: {
        session: {
          type: "http",
          scheme: "bearer",
          description: "A Clerk session token.",
        },
      },
    },
    security: [{ session: [] }],
  };
}
